### ISSUE TITLE
How to make a FFT for an array ?

### ISSUE THREAD

**Issue by pzg250** [peterhinch/micropython-fourier#1]
Hi Peter,
I am a pyboard D-series developer. I am finding a package of micropython that can do FFT. 
And I found your project, I think it's a great package. But I don't know how to use your package to make a FFT on an array, could you advise ? ( I use I2C protocol to collect data. )

Thanks in advance.

**Comment by peterhinch** [comment]
Section 4 of the docs aims to explain this. You can either store floating point data in the `.re` bound array or implement a populate function to do this. The [code here](https://github.com/peterhinch/micropython-fourier/blob/0723437e2556332f536c8a1c5f83f495f5c86634/dfttest.py#L60) illustrates populating the `.re` array with synthetic data.

**Comment by pzg250** [comment]
Hi Peter, 
Thank you for your reply. I still cannot quite understand. 
In normal python, I can use scipy fft. 
```
from scipy.fftpack import fft

x=np.linspace(0,1,8)
y = np.sin(x) # y is [0.0, 0.1423717, 0.2818428, 0.4155718, 0.5408342, 0.6550779, 0.7559753, 0.8414709]
yy = fft(y)
```
I got yy :
```
array([ 3.6331449 +0.j        , -0.60221606+1.13782668j,
       -0.496984  +0.45959321j, -0.47945237+0.18956166j,
       -0.47584004+0.j        , -0.47945237-0.18956166j,
       -0.496984  -0.45959321j, -0.60221606-1.13782668j])
```

And I try to use demo like,
```
from dfttest import *

dft = DFT(8)
y = [0.0, 0.1423717, 0.2818428, 0.4155718, 0.5408342, 0.6550779, 0.7559753, 0.8414709]
dft.re = array.array('f', y)

dft.run(FORWARD)
```

I got:
```
cartesian_print(dft)

Bin       real  imaginary
     0    0.00    0.00j
     1    0.14    0.00j
     2    0.28    0.00j
     3    0.42    0.00j
     4    0.54    0.00j
     5    0.66    0.00j
     6    0.76    0.00j
     7    0.84    0.00j
```

I think it's not the expected result. 

I'm not sure. Maybe my usage is wrong ? 

Regards,

**Comment by peterhinch** [comment]
This is an example of how to populate the real array:
```python
import dftclass
dft = dftclass.DFT(8)
for n, v in enumerate([0.0, 0.1423717, 0.2818428, 0.4155718, 0.5408342, 0.6550779, 0.7559753, 0.8414709]):
    dft.re[n] = v
```
I then ran the transform and viewed the result as follows:
```python
>>> dft.run(dftclass.FORWARD)
57
>>> dft.re
array('f', [0.454143, -0.075277, -0.06212299, -0.05993154, -0.05948, -0.05993154, -0.06212299, -0.075277])
>>> dft.im
array('f', [0.0, 0.1422283, 0.05744913, 0.0236952, 0.0, -0.0236952, -0.05744913, -0.1422283])
>>> 
```
A key point here that the dft class **.re** and **.im** arrays are single precision floats and must be so for the assembler code to work - you addressed this in your code. But you replaced the arrays created by the constructor with ones of your own. This won't work because the constructor has already set up the conditions for the assembler code based on the addresses of the arrays it has created.  This is for performance reasons. So in your example it performed the transforms with its own arrays which contained 0. Hence the zero result.

It is therefore essential to populate the arrays _in situ_ rather than replacing them with any other kind of object.

You may wish to do this via a **popfunc** - I produced the example above to illustrate the mechanics of populating them in-place.

**Comment by pzg250** [comment]
Hi Peter,
Thank you very much for your great help! It works when I use popfunc to set the re value.

```
y = [0, 0.1423717, 0.2818428, 0.4155718, 0.5408342, 0.6550779, 0.7559753, 0.8414709]

def popfunc(dft):
    for n, v in enumerate(y):
        dft.re[n] = v
```

And I have last question, do you know why the result is different from scipy result ?

**Comment by peterhinch** [comment]
I'm afraid I don't. There is clearly a scaling difference: bin 0 should contain the mean DC component - the sum of all the inputs divided by the number of samples. My calculator confirms the value produced by the MicroPython code. Unfortunately I have not used scipy so can't comment on its results.

Off the top of my head I don't know what the DFT of a repeated quarter sinewave should look like. Unless you do, or feel like doing the maths, I suggest testing with sample sets having known or self-evident transforms: a single cycle of sinewave, N cycles, a single cycle of squarewave, an impulse function, and so on.

This is how I tested the code. Also by comparison with other DFT code with various sample sets.

**Comment by pzg250** [comment]
Thank you very much. I will continue investing on this. Let me close this for now.
