### ISSUE TITLE
Converting from other library

### ISSUE THREAD

**Issue by francescofact** [peterhinch/micropython-fourier#2]
Hi, 
i have some code for arduino written in C with the library "arduinoFTT.h". I'm using an esp32 with micropython firmware so i need to translate that code to micropython.
The ftt related lines are:
` FFT.Windowing(vReal, SAMPLES, FFT_WIN_TYP_HAMMING, FFT_FORWARD);
  FFT.Compute(vReal, vImag, SAMPLES, FFT_FORWARD);
  FFT.ComplexToMagnitude(vReal, vImag, SAMPLES);
`
where the values are these:
#define SAMPLES 512 
double vReal[SAMPLES];

I can't understand how to convert to this library.
Can someone help me please?

**Comment by peterhinch** [comment]
This fft library uses STM assembler: it is intended for Pyboards and won't run on ESP32. I suggest you raise a general query on [the forum](http://forum.micropython.org/index.php).
