### ISSUE TITLE
Runs only on PyBoard not on ESP devices.

### ISSUE THREAD

**Issue by akshay-since1987** [peterhinch/micropython-fourier#3]
This doesn't work on ESP running Micropython. It fails to import pyb. I do not understand why the code is device dependent. Kindly help if possible.

**Comment by peterhinch** [comment]
The `micropython-fourier` library is written in Arm Thumb V7 assembly language and is therefore not portable to Espressif devices. The `pyb` library is also specific to Pyboards: you should use `machine` on other targets.
